### ISSUE TITLE
We have a private registry with Nexus.

### ISSUE THREAD

**Issue by mnlservices** [sous-chefs/docker#1002]
### Cookbook version
[Version of the cookbook where you are encountering the issue]

### Chef-client version
[Version of chef-client in your environment]

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by dickmuller** [comment]
Hi,

We have a private registry with Nexus.
Together with Chef and the docker cookbook this works great.

But now I have come to a problem when I build an image and want to push that image to our nexus registry.
The build works, but the push doesn't result in anything.

I see the task during converge, but nothing is done and no error raised.
Is this a known error?

Kind regards,
Dick Muller

**Comment by darkn3rd** [comment]
Could you try this out with Chef Server 13 or Chef Server 14?  Chef Server 12 has past End of Life.

**Comment by dickmuller** [comment]
OK, I will check this sometime this week.
Thanks for your suggestion.

Kind regards,
Dick

**Comment by dheerajd-msys** [comment]
@dickmuller Could you please confirm about ^ ?
