### ISSUE TITLE
Management of the docker-ce-cli package

### ISSUE THREAD

**Issue by dud225** [sous-chefs/docker#1111]
Hello

this cookbook can manage the docker-ce package, however the CLI is provided from a separate package in the Docker repository. We may end up in situation where both are not update:
```
Client: Docker Engine - Community
 Version:           19.03.8
 [...]

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
```

Is there any particular reason of not managing the docker-ce-cli package as well?

**Comment by dheerajd-msys** [comment]
@btm @tas50 We may require your thoughts on ^

**Comment by bkonick** [comment]
@dud225 i actually came across this recently when the API version of docker-ce-cli finally drifted too far away from the version of docker-ce we were installing. I made a workaround resource in our wrapper that does a package swap to whatever version of docker we are trying to install.

I'd be in favor of keeping the two package versions in sync.

**Comment by dud225** [comment]
Yes that's what I initially wanted to do but as I realized that I would have to duplicate [the tedious code that builds the proper version string](https://github.com/chef-cookbooks/docker/blob/6ac74789e3e804b30c9da55db43d35495b7b9d24/libraries/docker_installation_package.rb#L64) I gave up.
