### ISSUE TITLE
docker_container log_driver should support "local"

### ISSUE THREAD

**Issue by timorkal** [sous-chefs/docker#1125]
Hello,

Currently I don't see any support for "local" driver in the docker_container log_driver option.
As per docker documantation: https://docs.docker.com/config/containers/logging/local/ - this is possible to achieve.

I know that "local" is the default behavior but in my case I use "gelf" as the default driver and I would like to have "local" for particular containers but keeping "gelf" as the default one.

Thanks

**Comment by zakame** [comment]
Probably two places to update, I can make a PR :muscle: :

- `dockerd` configuration https://github.com/sous-chefs/docker/blob/24e57270388b582f85cac495f68729b6468f35ad/libraries/docker_service_base.rb#L54
- per-container override https://github.com/sous-chefs/docker/blob/e3c0b84b2f4e0dcfbe91d92dced10a74413ec95f/libraries/docker_container.rb#L38
