### ISSUE TITLE
Is there any intention to support RHEL 8.2?

### ISSUE THREAD

**Issue by Ashpigelman** [sous-chefs/docker#1127]
Hi @someara @bflad @chasebolt 

I have a question please,
Is there any intention to support RHEL 8.2 and when ?
Right now the link support only in version RHEL 7:  https://download.docker.com/linux/centos/
The last update was in 18 in October 2019 and since than release more versions.
I am waiting for your response, Thank you.
Alexey

**Comment by ramereth** [comment]
This is actually resolved a while ago.
