### ISSUE TITLE
Support multiple registry mirrors for the docker service

### ISSUE THREAD

**Issue by DaniJG** [sous-chefs/docker#1144]
## Problem Statement

Currently the `docker_service` resource allows a registry mirror to be configured using the `registry_mirror` property, which gets propagated as the `--registry-mirror`

However, one might want to configure multiple mirrors, ie add multiple `--registry-mirror` arguments to the daemon. Currently there is no way to do so unless using the `misc_opts` as a workaround (see alternatives below).

## :grey_question: Possible Solution

A possible way to fix it could be:
- Update the paramter type as `[String, Array]` in https://github.com/sous-chefs/docker/blob/master/libraries/docker_service_base.rb#L59
- Add as many times as necessary the `--registry-mirror` argument in https://github.com/sous-chefs/docker/blob/master/libraries/helpers_service.rb#L235

PS. I would be happy to send a PR for this. However I am not super familiar with the codebase, so I might be missing something in the solution.

## :arrow_heading_up: Describe alternatives you've considered

Currently this can be achieved using `misc_opts` as a workaround
```
docker_service 'default' do
  action [:start]
  ...
  registry_mirror 'https://mirror.gcr.io'
  misc_opts "--registry-mirror=https://my-mirror.contoso.io"
end
```

## :heavy_plus_sign: Additional context

This might be helpful given the recent change in the Docker Hub pull rate limit. For example, one might want to setup google cloud's mirror plus your own mirror.

**Comment by ramereth** [comment]
@DaniJG please feel free to create a PR which addresses this. We can review and get it merged!
