### ISSUE TITLE
README.md is missing resources / broken links

### ISSUE THREAD

**Issue by rmoriz** [sous-chefs/docker#1202]
Hi,

the main readme misses the documentaton for some resources e.g. `docker_image`. As far as I can see parts of the documentation were sadly removed and stored in extra files but the links in https://github.com/sous-chefs/docker#resources-overview were never updated.

example commit:

https://github.com/sous-chefs/docker/commit/e8372ca3abd0570e6b261d512d2484140d0daa6f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by damacus** [comment]
Fixed by #1293
