### ISSUE TITLE
Setting a version causes a service restart on every run

### ISSUE THREAD

**Issue by pdohertybcov** [sous-chefs/docker#1203]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Setting `version` in the `docker_service` resource will cause docker to be restarted on every chef run, even if the version matches what's installed.

## :pancakes: Cookbook version

7.7.8

## :woman_cook:  Chef-Infra Version

16.16.13

## :tophat: Platform details

CentOS 7.6 and 7.7

## Steps To Reproduce

1. Create a recipe with:
```
docker_service 'default' do
  action [:create, :start]
  version '20.10.10'
end
```

2. Run chef, docker is installed and started.
3. Run chef again, docker will be restarted.
4. GOTO 3

## :police_car: Expected behavior

Docker shouldn't be restarted unless the package installation actually changes something.

## :heavy_plus_sign: Additional context

```
             * yum_package[docker-ce] action install
        - install version 20.10.10 of package docker-ce

           * docker_service[default] action restart
             * docker_service_manager_systemd[default] action restart
        * service[docker] action disable
          - disable service service[docker]
        * service[docker] action stop
          - stop service service[docker]
        * directory[/usr/libexec/docker] action create (up to date)
        * template[/usr/libexec/docker/docker-wait-ready] action create (up to date)
        * template[/lib/systemd/system/docker.socket] action create (up to date)
        * directory[/etc/containerd] action create (up to date)
        * file[/etc/containerd/config.toml] action create_if_missing (up to date)
        * template[/etc/systemd/system/containerd.service] action create (skipped due to not_if)
        * template[/lib/systemd/system/docker.service] action create (up to date)
        * template[/etc/systemd/system/docker.socket] action create (up to date)
        * template[/etc/systemd/system/docker.service] action create (up to date)
        * execute[systemctl daemon-reload] action nothing (skipped due to action :nothing)
        * execute[systemctl try-restart docker] action nothing (skipped due to action :nothing)
        * service[docker] action enable
          - enable service service[docker]
        * service[docker] action start
          - start service service[docker]
```

**Comment by ramereth** [comment]
@pdohertybcov looks like you're using an older version of this cookbook. Can you please confirm this is still happening with the most recent version?

**Comment by pdohertybcov** [comment]
oops, I thought I checked that.  Unfortunately updating to `10.1.1` is still giving me the same behavior.  I tried changing the version between `20.10.10`, `20.10.10-3`, and `20.10.10-3.el7` But that didn't help.  `20.10.10-3` fails because yum doesn't accept that.

The issue seems to be in the yum_package resource is seeing a change, but I don't understand why.

```
         * yum_package[docker-ce] action install
        - install version 20.10.10-3.el7 of package docker-ce

           * docker_service[default] action restart
             * docker_service_manager_systemd[default] action restart
        * service[docker] action disable
          - disable service service[docker]
        * service[docker] action stop
          - stop service service[docker]
```

**Comment by ramereth** [comment]
@pdohertybcov Oh I remember why this is happening. You need to prepend the version with the package epoch (which upstream has set. Could you try `3:20.10.10` please?

**Comment by pdohertybcov** [comment]
🎉 Thanks.  That did the trick, and works as expected.  I've run into issues with how the Chef package resource handles versions before, but this is the first time I've encountered this fix.  Thanks again.
