### ISSUE TITLE
docker_installation_tarball group is always reset

### ISSUE THREAD

**Issue by benpro** [sous-chefs/docker#1205]
In [docker_installation_tarball.rb#L84](https://github.com/sous-chefs/docker/blob/efc56abaf4a7012a8b22ad07ce6a5e57abd83dc5/libraries/docker_installation_tarball.rb#L84) the group resource is always resetting the docker group if there are members in it:

```
      * group[docker] action create[2021-11-11T06:50:43+00:00] INFO: group[docker] altered: replace group members with new list of members:

        - alter group docker
        - replace group members with new list of members: <<< Remove all my members :(
```

> How members should be appended and/or removed from a group. When true, members are appended and excluded_members are removed. When false, group members are reset to the value of the members property.

Here we are in the group members reset behavior.
I believe a patch is to add property `append true` to the `group` resource.

**Comment by ramereth** [comment]
@benpro please feel free to make a PR which resolves this and we can review it!
