### ISSUE TITLE
docker Chef 18 compatibility

### ISSUE THREAD

**Issue by djessich** [sous-chefs/docker#1222]
## :ghost: Brief Description

When executing `docker_service` resource (maybe others from libraries folder too?) from this cookbook, its configured values in resource properties are ignored when running with Chef 18.

## :pancakes: Cookbook version

10.2.4

## :woman_cook:  Chef-Infra Version

18.0.185

## :tophat: Platform details

Docker Container running with Test Kitchen (e.g. RHEL 8)

## Steps To Reproduce

Run

```
docker_service 'default' do
  install_method 'package'
  setup_docker_repo false
  group 'someothergroup' # <-- does not work
  action [:create, :start]
end
```

will render in `/etc/systemd/system/docker.service`

```
# TRUNCATED OUTPUT
ExecStart=/usr/bin/dockerd  --group=docker --pidfile=/var/run/docker.pid --containerd=/run/containerd/containerd.sock
# TRUNCATED OUTPUT
```

## :police_car: Expected behavior

Should render in `/etc/systemd/system/docker.service`

```
# TRUNCATED OUTPUT
ExecStart=/usr/bin/dockerd  --group=someothergroup --pidfile=/var/run/docker.pid --containerd=/run/containerd/containerd.sock
# TRUNCATED OUTPUT
```

Pls mind `--group=someothergroup` as configured by resource properties.

## :heavy_plus_sign: Additional context

Works fine with Chef 17.

Maybe somehow related to unified_mode that became enabled with Chef 18 by default?

**Comment by djessich** [comment]
After searching around the issue its definitely a problem with unified_mode. By setting `DockerCookbook::DockerService.unified_mode(false)` from within my wrapper cookbook, the values are correctly set, so my example above works like a charm.

**Comment by Stromweld** [comment]
If you can submit a PR for that we'd happily review it and get it released.

**Comment by djessich** [comment]
@Stromweld Unfortunately, its not that easy to implement "correctly". Well you may be able to add `unified_mode false` to the custom resources defined in libraries but this makes it incompatible with unified mode. I think it is better to refactor all resources in libraries folder to custom resources, but this requires very deep knowledge in functional requirements for this cookbook which I do not have.

**Comment by b-dean** [comment]
@djessich, I may be misunderstanding Chef's [documentation](https://docs.chef.io/unified_mode/) on `unified_mode`, but it seems like the change in Chef 18 is that `unified_mode` is true by default. Not true _always_, it still is something resources can set to false. But by _default_ it is true in Chef 18. It's not that it can only work in unified mode. Seems like it is still valid to set `unified_mode false` for resources that cannot use it.

In fact, I think that's why they're even saying something, so people will know, "hey this is the new default, so fix your stuff" either by making it work with unified mode, or specifically disabling unified mode for the resources.

**Comment by ramereth** [comment]
@b-dean it's our standard to enable it by default as it fixes a lot of issues in the long term. So it needs to be fixed and we cannot simply just disable it for now as it will likely cause other issues too.

**Comment by b-dean** [comment]
Sure, and that's fine, but in the meantime anyone using this cookbook is stuck on Chef 17, which is frustrating.

**Comment by ramereth** [comment]
@b-dean I completely agree. Anyone is more than welcome to work on a proper fix. I unfortunately don't have any time at the moment.
