### ISSUE TITLE
docker-ce package name in ubuntu 22.04 is in a different format that affects module 'docker_installation_package'

### ISSUE THREAD

**Issue by sidxz** [sous-chefs/docker#1224]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The docker-ce package name in ubuntu 22.04 is in format ```5:20.10.21~3-0~ubuntu-jammy. ```
The docker_installation_package does not append the codename properly.

## :pancakes: Cookbook version

10.2.2

## :woman_cook:  Chef-Infra Version

18.0

## :tophat: Platform details

default-ubuntu-2204 5.15.0-30-generic

## Steps To Reproduce

1. use apt_repository to add docker rep
"https://download.docker.com/linux/#{node['platform']}"

2. Then Run
```
docker_installation_package 'default' do
  version '20.10.21'
  action :create
end
```
in ubuntu 22.04 

## :police_car: Expected behavior

Install the specified docker version

## :heavy_plus_sign: Additional context

I believe this part of the code needs to be updated to append the codename.
docker/libraries/docker_installation_package.rb
```
elsif jammy? # ubuntu 22.04
   'jammy'
end
```

**Comment by Raboo** [comment]
resolved by #1225
