### ISSUE TITLE
missing a 1.13 way to control CPU limit

### ISSUE THREAD

**Issue by keithyau** [sous-chefs/docker#818]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
Chef 12

### Chef-client version
[Version of chef-client in your environment]
chef 12

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
AWS / CentOS

### Scenario:
[What you are trying to achieve and you can't?]
From Docker.com doc: https://docs.docker.com/engine/admin/resource_constraints/

Docker 1.13 and higher:
docker run -it --cpus=".5" ubuntu /bin/bash

But in this cookbook, i can only find CPU_shares which is a 1.12 way

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
CPU Can limit

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
No this option in conf

**Comment by someara** [comment]
Hi!

Thanks for pointing this out and reminding me that there are quite a few things that need to be updated for the v1.26 version of the remote API

This needs to be walked through and audited for modernity: https://docs.docker.com/engine/api/v1.26/

-s

**Comment by vnandha** [comment]
I am interested in this feature too. Mainly **cpu_quota** would help to set the cpu limits.

**Comment by vnandha** [comment]
is there any instruction how to contribute, we really need this feature.
