### ISSUE TITLE
Provide build-time argument with docker_image resource

### ISSUE THREAD

**Issue by fetherolfjd** [sous-chefs/docker#827]
This may be a feature request, rather than a bug. Is it possible to provide a build time argument with the docker_image resource? Thus making it analogous to the command: ```docker build --build-arg ENVIRONMENT=production -f dockerfiles/Dockerfile .```

### Cookbook version
2.13.10

### Chef-client version
12.5.1

### Platform Details
Ubuntu 14.04.5 LTS

### Scenario:
Trying to copy specific files into a configuration directory based on the environment being set up, i.e. production, integration, test, etc.

**Comment by someara** [comment]
Absolutely. That's one of the things that showed up in the API after the initial resource implementation. Should be straight forward to implement.

**Comment by salsa-dev** [comment]
+1 really useful feature

i will have a look into implementation

**Comment by damacus** [comment]
Build args have been supported for a while. Closing 👍🏼
