### ISSUE TITLE
Please add support for labels for volumes

### ISSUE THREAD

**Issue by EugenMayer** [sous-chefs/docker#856]
Support for labels would be very nice

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by spuder** [comment]
What exactly are you looking for? The cookbook already does support labels

    labels A string or array to set metadata on the daemon in the form ['foo:bar', 'hello:world']`
