### ISSUE TITLE
Possibility to remove unused docker images

### ISSUE THREAD

**Issue by spotlesscoder** [sous-chefs/docker#956]
I want to be able to remove unused docker images in a similar way like I can do in portainer.io's UI:

![image](https://user-images.githubusercontent.com/25173078/34880918-3fc5189a-f7b2-11e7-84cd-1f8cc49266d7.png)

Is there a recipe for this which should automatically find unused images and delete all of them in a configurable interval

**Comment by chasebolt** [comment]
Spotify has a garbage collection container that clean up old images. I run
this on a cron schedule on all my docker instances. I can dig up the url
for it later, if you can’t find it.

**Comment by tas50** [comment]
There's an API call in docker-api for this that we should probably look at.

**Comment by tas50** [comment]
https://docs.docker.com/engine/api/v1.35/#operation/ImagePrune

**Comment by CodingSpiderFox** [comment]
Unfortunately I don't have the time at the moment to look into it. Hopefully this will change in a few weeks
